name: API Endpoint Check

on: 
  push:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gist
        uses: actions/checkout@d1cef55e
        with:
          gist: miron/b342203fc208d541378ff64b2236f55f
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}  
      - name: Fetch BPs and Urls
        run: |
          BPS=`curl -s  api.eosn.io/v1/chain/get_producers -d '{"limit": "68", "json": true}' | 
          jq -r '.rows[] | .url'`
          while read bp; do
            if sane=`curl -s -L -m 10 "$bp/json"`; then
              echo "$sane" | jq -j -r '.nodes | .[].api_endpoint | select(. == null | not) + " "'
            else
              continue
            done <<< "$BP"
          fi
      - name: Commit Files
        run: |
          git config --local user.name "miron"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "fresh BP list"
            git push
          fi
