name: API Check

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch BPs and Urls
        run:  |
          curl -s  api.eosn.io/v1/chain/get_producers -d '{"limit": "68", "json": true}' | jq '.rows[] | .owner + " " +  .url' > bps.md
      - name: Commit Files
        run: |
          git config --local user.name "miron"
          git commit -m "fresh BP list" -a
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

