name: API Endpoint Check

on: 
  push:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gist
        uses: actions/checkout@d1cef55e
        with:
          gist: miron/b342203fc208d541378ff64b2236f55f
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}  
      - name: Fetch BPs and Urls
        run: |
          BPS=`curl -s api.eosn.io/v1/chain/get_producers -d '{"limit": "69", "json": true}' | 
          jq -r '.rows[] | .url'`
          while read bp; do
            if sane=`curl -s -L -m 10 -k "$bp/bp.json"`; then 
              jq -j -r '.producer_account_name + " "' <<< $sane || continue
              jq -j -r 'if (.org.social.github | length) > 0  then "[@"+.org.social.github+"](https://github.com/"+.org.social.github+")" else empty end + " "' <<< $sane || continue
              jq -j -r 'if (.org.social.github_user | length) > 0 then "[@"+.org.social.github_user+"](https://github.com/"+.org.social.github_user+")" else empty end + " "' <<< $sane || continue 
              jq -j -r '[.nodes[]|select(.api_endpoint)| .api_endpoint]|unique[]' <<< $sane || continue
              printf " \n"
            else
              continue
            fi
          done <<< "$BPS" > BP.md
      - name: Commit Files
        run: |
          git config --local user.name "miron"
          if [ -n "$(git status --porcelain)" ]; then
            git pull
            git add .
            git commit -m "fresh BP list"
            git push
          fi
