name: API Check

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: check out with ssh
        #run: git remote set-url origin git@github.com:b342203fc208d541378ff64b2236f55f.git
        #with:
         # name: miron/b342203fc208d541378ff64b2236f55f
          #token: ${{ secrets.my_pat }}
          #ref: refs/heads/release
      #- name: Clone Gist
        #run: git clone git@github.com:b342203fc208d541378ff64b2236f55f.git

      - name: Readme Text
        run: >
          echo 'Scheduled Github Action checking every hour top 68 BPs on EOS for homepage  
          as returned by get_producers, appending and extracting api_endpoints.   
          ToDo:  
          - check sites for other locations than main path for bp.json  
          - check for payment so that BPs are not at fixed 68 value  
          - rotate used api for curl  
            
          ' > README.md
      - name: Fetch BPs and Urls
        run: |
          BPS=`curl -s  api.eosn.io/v1/chain/get_producers -d '{"limit": "68", "json": true}' | 
          jq -r '.rows[] | .url'`
          for value in $BPS
          do
            curl -s -L -m 10 $value/bp.json | jq -r '.nodes | .[].api_endpoint | select(. == null | not) + "  "' || continue
          done > BPs.md
      - name: Commit Files
        if: always()
        run: |
          git remote add origin git@github.com:b342203fc208d541378ff64b2236f55f.git
          #git config --local user.name "miron"
          git config --global user.name "miron"
          git checkout master
          #git add .
          #git commit -m "fresh BP list"
          #git push origin HEAD:master
          git push -u origin master
      #- name: Push Changes
       # if: always()
        #uses: ad-m/github-push-action@master
        #with:
         # github_token: ${{ secrets.GITHUB_TOKEN }}

