name: API Check

on: 
  push:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gist
        uses: actions/checkout@d1cef55e
        with:
          gist: miron/b342203fc208d541378ff64b2236f55f
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}  
      - name: Readme Text
        run: >
          echo 'Scheduled Github Action checking every hour top 68 BPs on EOS for homepage  
          as returned by get_producers, appending and extracting api_endpoints.   
          ToDo:  
          - check sites for other locations than main path for bp.json  
          - check for payment so that BPs are not at fixed 68 value  
          - rotate used api for curl  
            
          ' > README.md
      - name: Fetch BPs and Urls
        run: |
          BPS=`curl -s  api.eosn.io/v1/chain/get_producers -d '{"limit": "68", "json": true}' | 
          jq -r '.rows[] | .url'`
          for value in $BPS
          do
            curl -s -L -m 10 $value/bp.json | jq -r '.nodes | .[].api_endpoint | select(. == null | not) + "  "' || continue
          done > BPs.md
      - name: Commit Files
        run: |
          git config --local user.name "miron"
          git add .
          git commit -m "fresh BP list"
          git push
