name: API Check

on: 
  #push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Readme Text
        run: >
          echo 'Scheduled Github Action which checks every hour the top 68 BPs on EOS for Homepage 
          as returned by get_producers, appends bp.json to site and extracts api_endpoint. 
          ToDo: catch parse errors, check site for other locations than main path for bp.json, 
          set timeout, check for payment so that BPs are not at fixed 68 value.' > README.md
      - name: Fetch BPs and Urls
        run: |
          BPS=`curl -s  api.eosn.io/v1/chain/get_producers -d '{"limit": "68", "json": true}' | 
          jq -r '.rows[] | .url'`
          for value in $BPS
          do
            curl -s -L -m 10 $value/bp.json | jq -r '.nodes | .[].api_endpoint | select(. == null | not) + "  "' || continue
          done >> README.md
      - name: Commit Files
        if: always()
        run: |
          git config --local user.name "miron"
          git add .
          git commit -m "fresh BP list"
      - name: Push Changes
        if: always()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

