name: API Check

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'

jobs:
  get_bps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch BPs and Urls
        run:  |
          BPS=`curl -s  api.eosn.io/v1/chain/get_producers -d '{"limit": "68", "json": true}' | 
          jq -r '.rows[] | .owner + " " +  .url'`
          for value in $BPS
          do
            curl -s $value/bp.json | jq -r '.nodes | .[].api_endpoint'  
          done
      - name: Commit Files
        run: |
          git config --local user.name "miron"
          git add .
          git commit -m "fresh BP list"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

